apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediamtx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediamtx
  template:
    metadata:
      labels:
        app: mediamtx
    spec:
      containers:
      - name: mediamtx
        image: bluenviron/mediamtx:latest
        ports:
        - containerPort: 8554
          name: rtsp
        - containerPort: 8888
          name: hls
        - containerPort: 8889
          name: webrtc
        volumeMounts:
        - name: config
          mountPath: /mediamtx.yml
          subPath: mediamtx.yml
      volumes:
      - name: config
        configMap:
          name: mediamtx-config
