apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespaces.yaml
  - argocd.yaml
  - redpanda-simple.yaml
  - redpanda-topic-job.yaml
  - minio-simple.yaml
  - postgresql/
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.1/manifests/install.yaml

