apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - argocd.yaml
  - redpanda.yaml
  - minio.yaml
  - redpanda-topic-job.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.1/manifests/install.yaml
