apiVersion: v1
kind: Service
metadata:
  name: training-controller
spec:
  selector:
    app: training-controller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
